### PR TITLE
Updated the component for support Polymer 1.0

### PR DESCRIPTION
**Pull request by cadwmaster**

### CODE REVIEW

**Comment by addyosmani** [comment]
This is great. Thanks! Mostly minor style nits.

**Comment by cadwmaster** [comment]
Any idea how to inject styles, now you can only use the style from the main page :(

**Comment by cadwmaster** [comment]
changes pushed !!!

**Comment by addyosmani** [comment]
Thanks for updating with the requested changes! I'm going to take another look at this this week and comment back if there's further updates required. Appreciate your work on this :tophat:

**Comment by addyosmani** [comment]
This will require a tiny bit more cleanup but its better than what we have in master. Landing.

**Pull request merged**
